
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.huawei.spg2800.v100r002c03;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-22T22:55:38.069-04:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SPG2800Service",
                      portName = "SPG2800Port",
                      targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03",
                      wsdlLocation = "file:/C:/codebase/BlueDiamond/SOAPClient/ws-client/src/main/resources/spg_service.wsdl",
                      endpointInterface = "com.huawei.spg2800.v100r002c03.SPG2800Port")
                      
public class SPG2800PortImpl implements SPG2800Port {

    private static final Logger LOG = Logger.getLogger(SPG2800PortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFNR(com.huawei.spg2800.v100r002c03.DeactCFNRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFNR(DeactCFNRRequest body) { 
        LOG.info("Executing operation deactCFNR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFVM(com.huawei.spg2800.v100r002c03.DeactCFVMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFVM(DeactCFVMRequest body) { 
        LOG.info("Executing operation deactCFVM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modTN(com.huawei.spg2800.v100r002c03.ModTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modTN(ModTNRequest body) { 
        LOG.info("Executing operation modTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFB(com.huawei.spg2800.v100r002c03.ActCFBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFB(ActCFBRequest body) { 
        LOG.info("Executing operation actCFB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplDRCW(com.huawei.spg2800.v100r002c03.RplDRCWRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplDRCW(RplDRCWRequest body) { 
        LOG.info("Executing operation rplDRCW");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCAPSCSCF(com.huawei.spg2800.v100r002c03.QueryCAPSCSCFRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCAPSCSCFResponse queryCAPSCSCF(QueryCAPSCSCFRequest body) { 
        LOG.info("Executing operation queryCAPSCSCF");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCAPSCSCFResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFS(com.huawei.spg2800.v100r002c03.DeactCFSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFS(DeactCFSRequest body) { 
        LOG.info("Executing operation deactCFS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSCR(com.huawei.spg2800.v100r002c03.DeactSCRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSCR(DeactSCRRequest body) { 
        LOG.info("Executing operation deactSCR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplSS(com.huawei.spg2800.v100r002c03.RplSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplSS(RplSSRequest body) { 
        LOG.info("Executing operation rplSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSnowBird(com.huawei.spg2800.v100r002c03.ActSnowBirdRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSnowBird(ActSnowBirdRequest body) { 
        LOG.info("Executing operation actSnowBird");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setOWSBR(com.huawei.spg2800.v100r002c03.SetOWSBRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setOWSBR(SetOWSBRRequest body) { 
        LOG.info("Executing operation setOWSBR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactNPAS4HSS(com.huawei.spg2800.v100r002c03.DeactNPAS4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactNPAS4HSS(DeactNPAS4HSSRequest body) { 
        LOG.info("Executing operation deactNPAS4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplSB(com.huawei.spg2800.v100r002c03.RplSBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplSB(RplSBRequest body) { 
        LOG.info("Executing operation rplSB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCap(com.huawei.spg2800.v100r002c03.QueryCapRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCapResponse queryCap(QueryCapRequest body) { 
        LOG.info("Executing operation queryCap");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCapResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvReferralMSG(com.huawei.spg2800.v100r002c03.RmvReferralMSGRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvReferralMSG(RmvReferralMSGRequest body) { 
        LOG.info("Executing operation rmvReferralMSG");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSS(com.huawei.spg2800.v100r002c03.DeactSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSS(DeactSSRequest body) { 
        LOG.info("Executing operation deactSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modSiFC(com.huawei.spg2800.v100r002c03.ModSiFCRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modSiFC(ModSiFCRequest body) { 
        LOG.info("Executing operation modSiFC");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modDevice(com.huawei.spg2800.v100r002c03.ModDeviceRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modDevice(ModDeviceRequest body) { 
        LOG.info("Executing operation modDevice");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modTNService(com.huawei.spg2800.v100r002c03.ServiceDataType  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modTNService(ServiceDataType body) { 
        LOG.info("Executing operation modTNService");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2IRS(com.huawei.spg2800.v100r002c03.AddTN2IRSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2IRS(AddTN2IRSRequest body) { 
        LOG.info("Executing operation addTN2IRS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addFMFM(com.huawei.spg2800.v100r002c03.AddFMFMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addFMFM(AddFMFMRequest body) { 
        LOG.info("Executing operation addFMFM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySpeedDial(com.huawei.spg2800.v100r002c03.QuerySpeedDialRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySpeedDialResponse querySpeedDial(QuerySpeedDialRequest body) { 
        LOG.info("Executing operation querySpeedDial");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySpeedDialResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modReferralMSG(com.huawei.spg2800.v100r002c03.ModReferralMSGRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modReferralMSG(ModReferralMSGRequest body) { 
        LOG.info("Executing operation modReferralMSG");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#drgUser(com.huawei.spg2800.v100r002c03.DrgUserRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType drgUser(DrgUserRequest body) { 
        LOG.info("Executing operation drgUser");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2Device4HSS(com.huawei.spg2800.v100r002c03.AddTN2Device4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2Device4HSS(AddTN2Device4HSSRequest body) { 
        LOG.info("Executing operation addTN2Device4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactNPAS(com.huawei.spg2800.v100r002c03.DeactNPASRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactNPAS(DeactNPASRequest body) { 
        LOG.info("Executing operation deactNPAS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvSub(com.huawei.spg2800.v100r002c03.RmvSubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvSub(RmvSubRequest body) { 
        LOG.info("Executing operation rmvSub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regSB(com.huawei.spg2800.v100r002c03.RegSBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regSB(RegSBRequest body) { 
        LOG.info("Executing operation regSB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addSiFC(com.huawei.spg2800.v100r002c03.AddSiFCRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addSiFC(AddSiFCRequest body) { 
        LOG.info("Executing operation addSiFC");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSS(com.huawei.spg2800.v100r002c03.ActSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSS(ActSSRequest body) { 
        LOG.info("Executing operation actSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySub4HSS(com.huawei.spg2800.v100r002c03.QuerySub4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySub4HSSResponse querySub4HSS(QuerySub4HSSRequest body) { 
        LOG.info("Executing operation querySub4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySub4HSSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvIRSTN(com.huawei.spg2800.v100r002c03.RmvIRSTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvIRSTN(RmvIRSTNRequest body) { 
        LOG.info("Executing operation rmvIRSTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvPSISub(com.huawei.spg2800.v100r002c03.RmvPSISubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvPSISub(RmvPSISubRequest body) { 
        LOG.info("Executing operation rmvPSISub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryFMFM(com.huawei.spg2800.v100r002c03.QueryFMFMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryFMFMResponse queryFMFM(QueryFMFMRequest body) { 
        LOG.info("Executing operation queryFMFM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryFMFMResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvDevice(com.huawei.spg2800.v100r002c03.RmvDeviceRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvDevice(RmvDeviceRequest body) { 
        LOG.info("Executing operation rmvDevice");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actTN(com.huawei.spg2800.v100r002c03.ActTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actTN(ActTNRequest body) { 
        LOG.info("Executing operation actTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regDRCW(com.huawei.spg2800.v100r002c03.RegDRCWRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regDRCW(RegDRCWRequest body) { 
        LOG.info("Executing operation regDRCW");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actPreProv(com.huawei.spg2800.v100r002c03.ActPreProvRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actPreProv(ActPreProvRequest body) { 
        LOG.info("Executing operation actPreProv");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryBAR(com.huawei.spg2800.v100r002c03.QueryBARRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryBARResponse queryBAR(QueryBARRequest body) { 
        LOG.info("Executing operation queryBAR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryBARResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFVM(com.huawei.spg2800.v100r002c03.QueryCFVMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFVMResponse queryCFVM(QueryCFVMRequest body) { 
        LOG.info("Executing operation queryCFVM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFVMResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryRepData(com.huawei.spg2800.v100r002c03.QueryRepDataRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryRepDataResponse queryRepData(QueryRepDataRequest body) { 
        LOG.info("Executing operation queryRepData");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryRepDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFDA(com.huawei.spg2800.v100r002c03.QueryCFDARequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFDAResponse queryCFDA(QueryCFDARequest body) { 
        LOG.info("Executing operation queryCFDA");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFDAResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryLRI(com.huawei.spg2800.v100r002c03.QueryLRIRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryLRIResponse queryLRI(QueryLRIRequest body) { 
        LOG.info("Executing operation queryLRI");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryLRIResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setRepData(com.huawei.spg2800.v100r002c03.SetRepDataRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setRepData(SetRepDataRequest body) { 
        LOG.info("Executing operation setRepData");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setNPSSBR(com.huawei.spg2800.v100r002c03.SetNPSSBRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setNPSSBR(SetNPSSBRRequest body) { 
        LOG.info("Executing operation setNPSSBR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSpeedDial(com.huawei.spg2800.v100r002c03.DeactSpeedDialRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSpeedDial(DeactSpeedDialRequest body) { 
        LOG.info("Executing operation deactSpeedDial");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryNPSSBR(com.huawei.spg2800.v100r002c03.QueryNPSSBRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryNPSSBRResponse queryNPSSBR(QueryNPSSBRRequest body) { 
        LOG.info("Executing operation queryNPSSBR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryNPSSBRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFB(com.huawei.spg2800.v100r002c03.DeactCFBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFB(DeactCFBRequest body) { 
        LOG.info("Executing operation deactCFB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySS(com.huawei.spg2800.v100r002c03.QuerySSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySSResponse querySS(QuerySSRequest body) { 
        LOG.info("Executing operation querySS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#heartbeat(com.huawei.spg2800.v100r002c03.HeartbeatRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType heartbeat(HeartbeatRequest body) { 
        LOG.info("Executing operation heartbeat");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvFMFM(com.huawei.spg2800.v100r002c03.RmvFMFMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvFMFM(RmvFMFMRequest body) { 
        LOG.info("Executing operation rmvFMFM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryReferralMSG(com.huawei.spg2800.v100r002c03.QueryReferralMSGRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryReferralMSGResponse queryReferralMSG(QueryReferralMSGRequest body) { 
        LOG.info("Executing operation queryReferralMSG");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryReferralMSGResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryTNTASAddr(com.huawei.spg2800.v100r002c03.QueryTNTASAddrRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryTNTASAddrResponse queryTNTASAddr(QueryTNTASAddrRequest body) { 
        LOG.info("Executing operation queryTNTASAddr");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryTNTASAddrResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFB(com.huawei.spg2800.v100r002c03.QueryCFBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFBResponse queryCFB(QueryCFBRequest body) { 
        LOG.info("Executing operation queryCFB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFBResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFU(com.huawei.spg2800.v100r002c03.DeactCFURequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFU(DeactCFURequest body) { 
        LOG.info("Executing operation deactCFU");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvNPSSBR(com.huawei.spg2800.v100r002c03.RmvNPSSBRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvNPSSBR(RmvNPSSBRRequest body) { 
        LOG.info("Executing operation rmvNPSSBR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySub(com.huawei.spg2800.v100r002c03.QuerySubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySubResponse querySub(QuerySubRequest body) { 
        LOG.info("Executing operation querySub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySubResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPreProvDev2Sub(com.huawei.spg2800.v100r002c03.AddPreProvDev2SubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPreProvDev2Sub(AddPreProvDev2SubRequest body) { 
        LOG.info("Executing operation addPreProvDev2Sub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvDeviceTN(com.huawei.spg2800.v100r002c03.RmvDeviceTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvDeviceTN(RmvDeviceTNRequest body) { 
        LOG.info("Executing operation rmvDeviceTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFVM(com.huawei.spg2800.v100r002c03.ActCFVMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFVM(ActCFVMRequest body) { 
        LOG.info("Executing operation actCFVM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actNPAS(com.huawei.spg2800.v100r002c03.ActNPASRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actNPAS(ActNPASRequest body) { 
        LOG.info("Executing operation actNPAS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regComSS(com.huawei.spg2800.v100r002c03.RegComSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regComSS(RegComSSRequest body) { 
        LOG.info("Executing operation regComSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryPSISub(com.huawei.spg2800.v100r002c03.QueryPSISubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryPSISubResponse queryPSISub(QueryPSISubRequest body) { 
        LOG.info("Executing operation queryPSISub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryPSISubResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#preProv4HSS(com.huawei.spg2800.v100r002c03.PreProv4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType preProv4HSS(PreProv4HSSRequest body) { 
        LOG.info("Executing operation preProv4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFNR(com.huawei.spg2800.v100r002c03.QueryCFNRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFNRResponse queryCFNR(QueryCFNRRequest body) { 
        LOG.info("Executing operation queryCFNR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFNRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvSiFC(com.huawei.spg2800.v100r002c03.RmvSiFCRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvSiFC(RmvSiFCRequest body) { 
        LOG.info("Executing operation rmvSiFC");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySiFC(com.huawei.spg2800.v100r002c03.QuerySiFCRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySiFCResponse querySiFC(QuerySiFCRequest body) { 
        LOG.info("Executing operation querySiFC");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySiFCResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modFMFM(com.huawei.spg2800.v100r002c03.ModFMFMRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modFMFM(ModFMFMRequest body) { 
        LOG.info("Executing operation modFMFM");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryChargeID(com.huawei.spg2800.v100r002c03.QueryChargeIDRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryChargeIDResponse queryChargeID(QueryChargeIDRequest body) { 
        LOG.info("Executing operation queryChargeID");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryChargeIDResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setESRN(com.huawei.spg2800.v100r002c03.SetESRNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setESRN(SetESRNRequest body) { 
        LOG.info("Executing operation setESRN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactTN(com.huawei.spg2800.v100r002c03.DeactTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactTN(DeactTNRequest body) { 
        LOG.info("Executing operation deactTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSCR(com.huawei.spg2800.v100r002c03.ActSCRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSCR(ActSCRRequest body) { 
        LOG.info("Executing operation actSCR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPSISub(com.huawei.spg2800.v100r002c03.AddPSISubRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPSISub(AddPSISubRequest body) { 
        LOG.info("Executing operation addPSISub");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryRegisteredService(com.huawei.spg2800.v100r002c03.QueryRegisteredServiceRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryRegisteredServiceResponse queryRegisteredService(QueryRegisteredServiceRequest body) { 
        LOG.info("Executing operation queryRegisteredService");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryRegisteredServiceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actNPAS4HSS(com.huawei.spg2800.v100r002c03.ActNPAS4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actNPAS4HSS(ActNPAS4HSSRequest body) { 
        LOG.info("Executing operation actNPAS4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addCAPSCSCF(com.huawei.spg2800.v100r002c03.AddCAPSCSCFRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addCAPSCSCF(AddCAPSCSCFRequest body) { 
        LOG.info("Executing operation addCAPSCSCF");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFS(com.huawei.spg2800.v100r002c03.QueryCFSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFSResponse queryCFS(QueryCFSRequest body) { 
        LOG.info("Executing operation queryCFS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryServiceData(com.huawei.spg2800.v100r002c03.QueryServiceDataRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryServiceDataResponse queryServiceData(QueryServiceDataRequest body) { 
        LOG.info("Executing operation queryServiceData");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryServiceDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFNR(com.huawei.spg2800.v100r002c03.ActCFNRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFNR(ActCFNRRequest body) { 
        LOG.info("Executing operation actCFNR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryDevRegStatus(com.huawei.spg2800.v100r002c03.QueryDevRegStatusRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryDevRegStatusResponse queryDevRegStatus(QueryDevRegStatusRequest body) { 
        LOG.info("Executing operation queryDevRegStatus");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryDevRegStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#preProv(com.huawei.spg2800.v100r002c03.PreProvRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType preProv(PreProvRequest body) { 
        LOG.info("Executing operation preProv");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryDRCW(com.huawei.spg2800.v100r002c03.QueryDRCWRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryDRCWResponse queryDRCW(QueryDRCWRequest body) { 
        LOG.info("Executing operation queryDRCW");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryDRCWResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addReferralMSG(com.huawei.spg2800.v100r002c03.AddReferralMSGRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addReferralMSG(AddReferralMSGRequest body) { 
        LOG.info("Executing operation addReferralMSG");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySnowBird(com.huawei.spg2800.v100r002c03.QuerySnowBirdRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySnowBirdResponse querySnowBird(QuerySnowBirdRequest body) { 
        LOG.info("Executing operation querySnowBird");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySnowBirdResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#swapTN(com.huawei.spg2800.v100r002c03.SwapTNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType swapTN(SwapTNRequest body) { 
        LOG.info("Executing operation swapTN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryESRN(com.huawei.spg2800.v100r002c03.QueryESRNRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryESRNResponse queryESRN(QueryESRNRequest body) { 
        LOG.info("Executing operation queryESRN");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryESRNResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFDA(com.huawei.spg2800.v100r002c03.DeactCFDARequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFDA(DeactCFDARequest body) { 
        LOG.info("Executing operation deactCFDA");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySCR(com.huawei.spg2800.v100r002c03.QuerySCRRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySCRResponse querySCR(QuerySCRRequest body) { 
        LOG.info("Executing operation querySCR");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySCRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSpeedDial(com.huawei.spg2800.v100r002c03.ActSpeedDialRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSpeedDial(ActSpeedDialRequest body) { 
        LOG.info("Executing operation actSpeedDial");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPreProvDev2Sub4HSS(com.huawei.spg2800.v100r002c03.AddPreProvDev2Sub4HSSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPreProvDev2Sub4HSS(AddPreProvDev2Sub4HSSRequest body) { 
        LOG.info("Executing operation addPreProvDev2Sub4HSS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySB(com.huawei.spg2800.v100r002c03.QuerySBRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySBResponse querySB(QuerySBRequest body) { 
        LOG.info("Executing operation querySB");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QuerySBResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFS(com.huawei.spg2800.v100r002c03.ActCFSRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFS(ActCFSRequest body) { 
        LOG.info("Executing operation actCFS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modPUSIAS(com.huawei.spg2800.v100r002c03.ModPUSIASRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modPUSIAS(ModPUSIASRequest body) { 
        LOG.info("Executing operation modPUSIAS");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2Device(com.huawei.spg2800.v100r002c03.AddTN2DeviceRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2Device(AddTN2DeviceRequest body) { 
        LOG.info("Executing operation addTN2Device");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSnowBird(com.huawei.spg2800.v100r002c03.DeactSnowBirdRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSnowBird(DeactSnowBirdRequest body) { 
        LOG.info("Executing operation deactSnowBird");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setLRI(com.huawei.spg2800.v100r002c03.SetLRIRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setLRI(SetLRIRequest body) { 
        LOG.info("Executing operation setLRI");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#changeUName(com.huawei.spg2800.v100r002c03.ChangeUNameRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType changeUName(ChangeUNameRequest body) { 
        LOG.info("Executing operation changeUName");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFU(com.huawei.spg2800.v100r002c03.ActCFURequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFU(ActCFURequest body) { 
        LOG.info("Executing operation actCFU");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFU(com.huawei.spg2800.v100r002c03.QueryCFURequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFUResponse queryCFU(QueryCFURequest body) { 
        LOG.info("Executing operation queryCFU");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFUResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFDA(com.huawei.spg2800.v100r002c03.ActCFDARequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFDA(ActCFDARequest body) { 
        LOG.info("Executing operation actCFDA");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setCap(com.huawei.spg2800.v100r002c03.SetCapRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setCap(SetCapRequest body) { 
        LOG.info("Executing operation setCap");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvCAPSCSCF(com.huawei.spg2800.v100r002c03.RmvCAPSCSCFRequest  body )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvCAPSCSCF(RmvCAPSCSCFRequest body) { 
        LOG.info("Executing operation rmvCAPSCSCF");
        System.out.println(body);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
