package com.huawei.spg2800.v100r002c03;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-08-26T05:16:15.086-04:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", name = "SPG2800Port")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SPG2800Port {

    @WebResult(name = "DeactCFNRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFNR", action = "urn:#DeactCFNR")
    public GenericResponseType deactCFNR(
        @WebParam(partName = "body", name = "DeactCFNRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFNRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactCFVMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFVM", action = "urn:#DeactCFVM")
    public GenericResponseType deactCFVM(
        @WebParam(partName = "body", name = "DeactCFVMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFVMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModTN", action = "urn:#ModTN")
    public GenericResponseType modTN(
        @WebParam(partName = "body", name = "ModTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFB", action = "urn:#ActCFB")
    public GenericResponseType actCFB(
        @WebParam(partName = "body", name = "ActCFBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RplDRCWResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RplDRCW", action = "urn:#RplDRCW")
    public GenericResponseType rplDRCW(
        @WebParam(partName = "body", name = "RplDRCWRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RplDRCWRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCAPSCSCFResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCAPSCSCF", action = "urn:#QueryCAPSCSCF")
    public QueryCAPSCSCFResponse queryCAPSCSCF(
        @WebParam(partName = "body", name = "QueryCAPSCSCFRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCAPSCSCFRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactCFSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFS", action = "urn:#DeactCFS")
    public GenericResponseType deactCFS(
        @WebParam(partName = "body", name = "DeactCFSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactSCRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactSCR", action = "urn:#DeactSCR")
    public GenericResponseType deactSCR(
        @WebParam(partName = "body", name = "DeactSCRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactSCRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RplSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RplSS", action = "urn:#RplSS")
    public GenericResponseType rplSS(
        @WebParam(partName = "body", name = "RplSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RplSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActSnowBirdResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActSnowBird", action = "urn:#ActSnowBird")
    public GenericResponseType actSnowBird(
        @WebParam(partName = "body", name = "ActSnowBirdRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActSnowBirdRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetOWSBRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetOWSBR", action = "urn:#SetOWSBR")
    public GenericResponseType setOWSBR(
        @WebParam(partName = "body", name = "SetOWSBRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetOWSBRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactNPAS4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactNPAS4HSS", action = "urn:#DeactNPAS4HSS")
    public GenericResponseType deactNPAS4HSS(
        @WebParam(partName = "body", name = "DeactNPAS4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactNPAS4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RplSBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RplSB", action = "urn:#RplSB")
    public GenericResponseType rplSB(
        @WebParam(partName = "body", name = "RplSBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RplSBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCapResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCap", action = "urn:#QueryCap")
    public QueryCapResponse queryCap(
        @WebParam(partName = "body", name = "QueryCapRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCapRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvReferralMSGResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvReferralMSG", action = "urn:#RmvReferralMSG")
    public GenericResponseType rmvReferralMSG(
        @WebParam(partName = "body", name = "RmvReferralMSGRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvReferralMSGRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactSS", action = "urn:#DeactSS")
    public GenericResponseType deactSS(
        @WebParam(partName = "body", name = "DeactSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModSiFCResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModSiFC", action = "urn:#ModSiFC")
    public GenericResponseType modSiFC(
        @WebParam(partName = "body", name = "ModSiFCRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModSiFCRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModDeviceResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModDevice", action = "urn:#ModDevice")
    public GenericResponseType modDevice(
        @WebParam(partName = "body", name = "ModDeviceRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModDeviceRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModTNServiceResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModTNService", action = "urn:#ModTNService")
    public GenericResponseType modTNService(
        @WebParam(partName = "body", name = "ModTNServiceRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ServiceDataType body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddTN2IRSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddTN2IRS", action = "urn:#AddTN2IRS")
    public GenericResponseType addTN2IRS(
        @WebParam(partName = "body", name = "AddTN2IRSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddTN2IRSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddFMFMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddFMFM", action = "urn:#AddFMFM")
    public GenericResponseType addFMFM(
        @WebParam(partName = "body", name = "AddFMFMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddFMFMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySpeedDialResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySpeedDial", action = "urn:#QuerySpeedDial")
    public QuerySpeedDialResponse querySpeedDial(
        @WebParam(partName = "body", name = "QuerySpeedDialRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySpeedDialRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModReferralMSGResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModReferralMSG", action = "urn:#ModReferralMSG")
    public GenericResponseType modReferralMSG(
        @WebParam(partName = "body", name = "ModReferralMSGRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModReferralMSGRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DrgUserResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DrgUser", action = "urn:#DrgUser")
    public GenericResponseType drgUser(
        @WebParam(partName = "body", name = "DrgUserRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DrgUserRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddTN2Device4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddTN2Device4HSS", action = "urn:#AddTN2Device4HSS")
    public GenericResponseType addTN2Device4HSS(
        @WebParam(partName = "body", name = "AddTN2Device4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddTN2Device4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactNPASResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactNPAS", action = "urn:#DeactNPAS")
    public GenericResponseType deactNPAS(
        @WebParam(partName = "body", name = "DeactNPASRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactNPASRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvSubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvSub", action = "urn:#RmvSub")
    public GenericResponseType rmvSub(
        @WebParam(partName = "body", name = "RmvSubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvSubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RegSBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RegSB", action = "urn:#RegSB")
    public GenericResponseType regSB(
        @WebParam(partName = "body", name = "RegSBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RegSBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddSiFCResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddSiFC", action = "urn:#AddSiFC")
    public GenericResponseType addSiFC(
        @WebParam(partName = "body", name = "AddSiFCRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddSiFCRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActSS", action = "urn:#ActSS")
    public GenericResponseType actSS(
        @WebParam(partName = "body", name = "ActSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySub4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySub4HSS", action = "urn:#QuerySub4HSS")
    public QuerySub4HSSResponse querySub4HSS(
        @WebParam(partName = "body", name = "QuerySub4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySub4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvIRSTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvIRSTN", action = "urn:#RmvIRSTN")
    public GenericResponseType rmvIRSTN(
        @WebParam(partName = "body", name = "RmvIRSTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvIRSTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvPSISubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvPSISub", action = "urn:#RmvPSISub")
    public GenericResponseType rmvPSISub(
        @WebParam(partName = "body", name = "RmvPSISubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvPSISubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryFMFMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryFMFM", action = "urn:#QueryFMFM")
    public QueryFMFMResponse queryFMFM(
        @WebParam(partName = "body", name = "QueryFMFMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryFMFMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvDeviceResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvDevice", action = "urn:#RmvDevice")
    public GenericResponseType rmvDevice(
        @WebParam(partName = "body", name = "RmvDeviceRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvDeviceRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActTN", action = "urn:#ActTN")
    public GenericResponseType actTN(
        @WebParam(partName = "body", name = "ActTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RegDRCWResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RegDRCW", action = "urn:#RegDRCW")
    public GenericResponseType regDRCW(
        @WebParam(partName = "body", name = "RegDRCWRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RegDRCWRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActPreProvResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActPreProv", action = "urn:#ActPreProv")
    public GenericResponseType actPreProv(
        @WebParam(partName = "body", name = "ActPreProvRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActPreProvRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryBARResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryBAR", action = "urn:#QueryBAR")
    public QueryBARResponse queryBAR(
        @WebParam(partName = "body", name = "QueryBARRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryBARRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFVMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFVM", action = "urn:#QueryCFVM")
    public QueryCFVMResponse queryCFVM(
        @WebParam(partName = "body", name = "QueryCFVMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFVMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryRepDataResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryRepData", action = "urn:#QueryRepData")
    public QueryRepDataResponse queryRepData(
        @WebParam(partName = "body", name = "QueryRepDataRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryRepDataRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFDAResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFDA", action = "urn:#QueryCFDA")
    public QueryCFDAResponse queryCFDA(
        @WebParam(partName = "body", name = "QueryCFDARequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFDARequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryLRIResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryLRI", action = "urn:#QueryLRI")
    public QueryLRIResponse queryLRI(
        @WebParam(partName = "body", name = "QueryLRIRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryLRIRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetRepDataResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetRepData", action = "urn:#SetRepData")
    public GenericResponseType setRepData(
        @WebParam(partName = "body", name = "SetRepDataRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetRepDataRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetNPSSBRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetNPSSBR", action = "urn:#SetNPSSBR")
    public GenericResponseType setNPSSBR(
        @WebParam(partName = "body", name = "SetNPSSBRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetNPSSBRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactSpeedDialResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactSpeedDial", action = "urn:#DeactSpeedDial")
    public GenericResponseType deactSpeedDial(
        @WebParam(partName = "body", name = "DeactSpeedDialRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactSpeedDialRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryNPSSBRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryNPSSBR", action = "urn:#QueryNPSSBR")
    public QueryNPSSBRResponse queryNPSSBR(
        @WebParam(partName = "body", name = "QueryNPSSBRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryNPSSBRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactCFBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFB", action = "urn:#DeactCFB")
    public GenericResponseType deactCFB(
        @WebParam(partName = "body", name = "DeactCFBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySS", action = "urn:#QuerySS")
    public QuerySSResponse querySS(
        @WebParam(partName = "body", name = "QuerySSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "HeartbeatResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "Heartbeat", action = "urn:#Heartbeat")
    public GenericResponseType heartbeat(
        @WebParam(partName = "body", name = "HeartbeatRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        HeartbeatRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvFMFMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvFMFM", action = "urn:#RmvFMFM")
    public GenericResponseType rmvFMFM(
        @WebParam(partName = "body", name = "RmvFMFMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvFMFMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryReferralMSGResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryReferralMSG", action = "urn:#QueryReferralMSG")
    public QueryReferralMSGResponse queryReferralMSG(
        @WebParam(partName = "body", name = "QueryReferralMSGRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryReferralMSGRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryTNTASAddrResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryTNTASAddr", action = "urn:#NQueryTNTASAddr")
    public QueryTNTASAddrResponse queryTNTASAddr(
        @WebParam(partName = "body", name = "QueryTNTASAddrRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryTNTASAddrRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFB", action = "urn:#QueryCFB")
    public QueryCFBResponse queryCFB(
        @WebParam(partName = "body", name = "QueryCFBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactCFUResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFU", action = "urn:#DeactCFU")
    public GenericResponseType deactCFU(
        @WebParam(partName = "body", name = "DeactCFURequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFURequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvNPSSBRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvNPSSBR", action = "urn:#RmvNPSSBR")
    public GenericResponseType rmvNPSSBR(
        @WebParam(partName = "body", name = "RmvNPSSBRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvNPSSBRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySub", action = "urn:#QuerySub")
    public QuerySubResponse querySub(
        @WebParam(partName = "body", name = "QuerySubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddPreProvDev2SubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddPreProvDev2Sub", action = "urn:#AddPreProvDev2Sub")
    public GenericResponseType addPreProvDev2Sub(
        @WebParam(partName = "body", name = "AddPreProvDev2SubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddPreProvDev2SubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvDeviceTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvDeviceTN", action = "urn:#RmvDeviceTN")
    public GenericResponseType rmvDeviceTN(
        @WebParam(partName = "body", name = "RmvDeviceTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvDeviceTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFVMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFVM", action = "urn:#ActCFVM")
    public GenericResponseType actCFVM(
        @WebParam(partName = "body", name = "ActCFVMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFVMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActNPASResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActNPAS", action = "urn:#ActNPAS")
    public GenericResponseType actNPAS(
        @WebParam(partName = "body", name = "ActNPASRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActNPASRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RegComSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RegComSS", action = "urn:#RegComSS")
    public GenericResponseType regComSS(
        @WebParam(partName = "body", name = "RegComSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RegComSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryPSISubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryPSISub", action = "urn:#QueryPSISub")
    public QueryPSISubResponse queryPSISub(
        @WebParam(partName = "body", name = "QueryPSISubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryPSISubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "PreProv4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "PreProv4HSS", action = "urn:#PreProv4HSS")
    public GenericResponseType preProv4HSS(
        @WebParam(partName = "body", name = "PreProv4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        PreProv4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFNRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFNR", action = "urn:#QueryCFNR")
    public QueryCFNRResponse queryCFNR(
        @WebParam(partName = "body", name = "QueryCFNRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFNRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvSiFCResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvSiFC", action = "urn:#RmvSiFC")
    public GenericResponseType rmvSiFC(
        @WebParam(partName = "body", name = "RmvSiFCRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvSiFCRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySiFCResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySiFC", action = "urn:#QuerySiFC")
    public QuerySiFCResponse querySiFC(
        @WebParam(partName = "body", name = "QuerySiFCRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySiFCRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModFMFMResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModFMFM", action = "urn:#ModFMFM")
    public GenericResponseType modFMFM(
        @WebParam(partName = "body", name = "ModFMFMRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModFMFMRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryChargeIDResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryChargeID", action = "urn:#QueryChargeID")
    public QueryChargeIDResponse queryChargeID(
        @WebParam(partName = "body", name = "QueryChargeIDRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryChargeIDRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetESRNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetESRN", action = "urn:#SetESRN")
    public GenericResponseType setESRN(
        @WebParam(partName = "body", name = "SetESRNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetESRNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactTN", action = "urn:#DeactTN")
    public GenericResponseType deactTN(
        @WebParam(partName = "body", name = "DeactTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActSCRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActSCR", action = "urn:#ActSCR")
    public GenericResponseType actSCR(
        @WebParam(partName = "body", name = "ActSCRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActSCRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddPSISubResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddPSISub", action = "urn:#AddPSISub")
    public GenericResponseType addPSISub(
        @WebParam(partName = "body", name = "AddPSISubRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddPSISubRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryRegisteredServiceResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryRegisteredService", action = "urn:#QueryRegisteredService")
    public QueryRegisteredServiceResponse queryRegisteredService(
        @WebParam(partName = "body", name = "QueryRegisteredServiceRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryRegisteredServiceRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActNPAS4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActNPAS4HSS", action = "urn:#ActNPAS4HSS")
    public GenericResponseType actNPAS4HSS(
        @WebParam(partName = "body", name = "ActNPAS4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActNPAS4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddCAPSCSCFResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddCAPSCSCF", action = "urn:#AddCAPSCSCF")
    public GenericResponseType addCAPSCSCF(
        @WebParam(partName = "body", name = "AddCAPSCSCFRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddCAPSCSCFRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFS", action = "urn:#QueryCFS")
    public QueryCFSResponse queryCFS(
        @WebParam(partName = "body", name = "QueryCFSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryServiceDataResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryServiceData", action = "urn:#QueryServiceData")
    public QueryServiceDataResponse queryServiceData(
        @WebParam(partName = "body", name = "QueryServiceDataRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryServiceDataRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFNRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFNR", action = "urn:#ActCFNR")
    public GenericResponseType actCFNR(
        @WebParam(partName = "body", name = "ActCFNRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFNRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryDevRegStatusResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryDevRegStatus", action = "urn:#QueryDevRegStatus")
    public QueryDevRegStatusResponse queryDevRegStatus(
        @WebParam(partName = "body", name = "QueryDevRegStatusRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryDevRegStatusRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "PreProvResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "PreProv", action = "urn:#PreProv")
    public GenericResponseType preProv(
        @WebParam(partName = "body", name = "PreProvRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        PreProvRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryDRCWResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryDRCW", action = "urn:#QueryDRCW")
    public QueryDRCWResponse queryDRCW(
        @WebParam(partName = "body", name = "QueryDRCWRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryDRCWRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddReferralMSGResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddReferralMSG", action = "urn:#AddReferralMSG")
    public GenericResponseType addReferralMSG(
        @WebParam(partName = "body", name = "AddReferralMSGRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddReferralMSGRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySnowBirdResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySnowBird", action = "urn:#QuerySnowBird")
    public QuerySnowBirdResponse querySnowBird(
        @WebParam(partName = "body", name = "QuerySnowBirdRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySnowBirdRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SwapTNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SwapTN", action = "urn:#SwapTN")
    public GenericResponseType swapTN(
        @WebParam(partName = "body", name = "SwapTNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SwapTNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryESRNResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryESRN", action = "urn:#QueryESRN")
    public QueryESRNResponse queryESRN(
        @WebParam(partName = "body", name = "QueryESRNRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryESRNRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactCFDAResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactCFDA", action = "urn:#DeactCFDA")
    public GenericResponseType deactCFDA(
        @WebParam(partName = "body", name = "DeactCFDARequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactCFDARequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySCRResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySCR", action = "urn:#QuerySCR")
    public QuerySCRResponse querySCR(
        @WebParam(partName = "body", name = "QuerySCRRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySCRRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActSpeedDialResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActSpeedDial", action = "urn:#ActSpeedDial")
    public GenericResponseType actSpeedDial(
        @WebParam(partName = "body", name = "ActSpeedDialRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActSpeedDialRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddPreProvDev2Sub4HSSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddPreProvDev2Sub4HSS", action = "urn:#AddPreProvDev2Sub4HSS")
    public GenericResponseType addPreProvDev2Sub4HSS(
        @WebParam(partName = "body", name = "AddPreProvDev2Sub4HSSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddPreProvDev2Sub4HSSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QuerySBResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QuerySB", action = "urn:#QuerySB")
    public QuerySBResponse querySB(
        @WebParam(partName = "body", name = "QuerySBRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QuerySBRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFSResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFS", action = "urn:#ActCFS")
    public GenericResponseType actCFS(
        @WebParam(partName = "body", name = "ActCFSRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFSRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ModPUSIASResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ModPUSIAS", action = "urn:#ModPUSIAS")
    public GenericResponseType modPUSIAS(
        @WebParam(partName = "body", name = "ModPUSIASRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ModPUSIASRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "AddTN2DeviceResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "AddTN2Device", action = "urn:#AddTN2Device")
    public GenericResponseType addTN2Device(
        @WebParam(partName = "body", name = "AddTN2DeviceRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        AddTN2DeviceRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "DeactSnowBirdResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "DeactSnowBird", action = "urn:#DeactSnowBird")
    public GenericResponseType deactSnowBird(
        @WebParam(partName = "body", name = "DeactSnowBirdRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        DeactSnowBirdRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetLRIResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetLRI", action = "urn:#SetLRI")
    public GenericResponseType setLRI(
        @WebParam(partName = "body", name = "SetLRIRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetLRIRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ChangeUNameResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ChangeUName", action = "urn:#ChangeUName")
    public GenericResponseType changeUName(
        @WebParam(partName = "body", name = "ChangeUNameRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ChangeUNameRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFUResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFU", action = "urn:#ActCFU")
    public GenericResponseType actCFU(
        @WebParam(partName = "body", name = "ActCFURequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFURequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "QueryCFUResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "QueryCFU", action = "urn:#QueryCFU")
    public QueryCFUResponse queryCFU(
        @WebParam(partName = "body", name = "QueryCFURequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        QueryCFURequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "ActCFDAResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "ActCFDA", action = "urn:#ActCFDA")
    public GenericResponseType actCFDA(
        @WebParam(partName = "body", name = "ActCFDARequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        ActCFDARequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "SetCapResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "SetCap", action = "urn:#SetCap")
    public GenericResponseType setCap(
        @WebParam(partName = "body", name = "SetCapRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        SetCapRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );

    @WebResult(name = "RmvCAPSCSCFResponse", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", partName = "body")
    @WebMethod(operationName = "RmvCAPSCSCF", action = "urn:#RmvCAPSCSCF")
    public GenericResponseType rmvCAPSCSCF(
        @WebParam(partName = "body", name = "RmvCAPSCSCFRequest", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03")
        RmvCAPSCSCFRequest body,
        @WebParam(partName = "header", name = "Authentication", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        Authentication header,
        @WebParam(partName = "header", name = "ResendFlag", targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03", header = true)
        int header1
    );
}
