
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.huawei.spg2800.v100r002c03;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-08-26T05:16:14.849-04:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "SPG2800Service",
                      portName = "SPG2800Port",
                      targetNamespace = "http://www.huawei.com/SPG2800/V100R002C03",
                      wsdlLocation = "file:/C:/codebase/BlueDiamond/SOAPClient/ws-client/src/main/resources/spg_service.wsdl",
                      endpointInterface = "com.huawei.spg2800.v100r002c03.SPG2800Port")
                      
public class SPG2800PortImpl implements SPG2800Port {

    private static final Logger LOG = Logger.getLogger(SPG2800PortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFNR(com.huawei.spg2800.v100r002c03.DeactCFNRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFNR(DeactCFNRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFNR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFVM(com.huawei.spg2800.v100r002c03.DeactCFVMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFVM(DeactCFVMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFVM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modTN(com.huawei.spg2800.v100r002c03.ModTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modTN(ModTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFB(com.huawei.spg2800.v100r002c03.ActCFBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFB(ActCFBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplDRCW(com.huawei.spg2800.v100r002c03.RplDRCWRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplDRCW(RplDRCWRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rplDRCW");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCAPSCSCF(com.huawei.spg2800.v100r002c03.QueryCAPSCSCFRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCAPSCSCFResponse queryCAPSCSCF(QueryCAPSCSCFRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCAPSCSCF");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCAPSCSCFResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFS(com.huawei.spg2800.v100r002c03.DeactCFSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFS(DeactCFSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSCR(com.huawei.spg2800.v100r002c03.DeactSCRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSCR(DeactSCRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactSCR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplSS(com.huawei.spg2800.v100r002c03.RplSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplSS(RplSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rplSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSnowBird(com.huawei.spg2800.v100r002c03.ActSnowBirdRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSnowBird(ActSnowBirdRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actSnowBird");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setOWSBR(com.huawei.spg2800.v100r002c03.SetOWSBRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setOWSBR(SetOWSBRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setOWSBR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactNPAS4HSS(com.huawei.spg2800.v100r002c03.DeactNPAS4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactNPAS4HSS(DeactNPAS4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactNPAS4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rplSB(com.huawei.spg2800.v100r002c03.RplSBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rplSB(RplSBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rplSB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCap(com.huawei.spg2800.v100r002c03.QueryCapRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCapResponse queryCap(QueryCapRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCap");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCapResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvReferralMSG(com.huawei.spg2800.v100r002c03.RmvReferralMSGRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvReferralMSG(RmvReferralMSGRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvReferralMSG");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSS(com.huawei.spg2800.v100r002c03.DeactSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSS(DeactSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modSiFC(com.huawei.spg2800.v100r002c03.ModSiFCRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modSiFC(ModSiFCRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modSiFC");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modDevice(com.huawei.spg2800.v100r002c03.ModDeviceRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modDevice(ModDeviceRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modDevice");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modTNService(com.huawei.spg2800.v100r002c03.ServiceDataType  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modTNService(ServiceDataType body,Authentication header,int header1) { 
        LOG.info("Executing operation modTNService");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2IRS(com.huawei.spg2800.v100r002c03.AddTN2IRSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2IRS(AddTN2IRSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addTN2IRS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addFMFM(com.huawei.spg2800.v100r002c03.AddFMFMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addFMFM(AddFMFMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addFMFM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySpeedDial(com.huawei.spg2800.v100r002c03.QuerySpeedDialRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySpeedDialResponse querySpeedDial(QuerySpeedDialRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySpeedDial");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySpeedDialResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modReferralMSG(com.huawei.spg2800.v100r002c03.ModReferralMSGRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modReferralMSG(ModReferralMSGRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modReferralMSG");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#drgUser(com.huawei.spg2800.v100r002c03.DrgUserRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType drgUser(DrgUserRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation drgUser");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2Device4HSS(com.huawei.spg2800.v100r002c03.AddTN2Device4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2Device4HSS(AddTN2Device4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addTN2Device4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactNPAS(com.huawei.spg2800.v100r002c03.DeactNPASRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactNPAS(DeactNPASRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactNPAS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvSub(com.huawei.spg2800.v100r002c03.RmvSubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvSub(RmvSubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvSub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regSB(com.huawei.spg2800.v100r002c03.RegSBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regSB(RegSBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation regSB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addSiFC(com.huawei.spg2800.v100r002c03.AddSiFCRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addSiFC(AddSiFCRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addSiFC");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSS(com.huawei.spg2800.v100r002c03.ActSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSS(ActSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySub4HSS(com.huawei.spg2800.v100r002c03.QuerySub4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySub4HSSResponse querySub4HSS(QuerySub4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySub4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySub4HSSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvIRSTN(com.huawei.spg2800.v100r002c03.RmvIRSTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvIRSTN(RmvIRSTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvIRSTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvPSISub(com.huawei.spg2800.v100r002c03.RmvPSISubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvPSISub(RmvPSISubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvPSISub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryFMFM(com.huawei.spg2800.v100r002c03.QueryFMFMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryFMFMResponse queryFMFM(QueryFMFMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryFMFM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryFMFMResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvDevice(com.huawei.spg2800.v100r002c03.RmvDeviceRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvDevice(RmvDeviceRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvDevice");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actTN(com.huawei.spg2800.v100r002c03.ActTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actTN(ActTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regDRCW(com.huawei.spg2800.v100r002c03.RegDRCWRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regDRCW(RegDRCWRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation regDRCW");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actPreProv(com.huawei.spg2800.v100r002c03.ActPreProvRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actPreProv(ActPreProvRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actPreProv");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryBAR(com.huawei.spg2800.v100r002c03.QueryBARRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryBARResponse queryBAR(QueryBARRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryBAR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryBARResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFVM(com.huawei.spg2800.v100r002c03.QueryCFVMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFVMResponse queryCFVM(QueryCFVMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFVM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFVMResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryRepData(com.huawei.spg2800.v100r002c03.QueryRepDataRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryRepDataResponse queryRepData(QueryRepDataRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryRepData");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryRepDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFDA(com.huawei.spg2800.v100r002c03.QueryCFDARequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFDAResponse queryCFDA(QueryCFDARequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFDA");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFDAResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryLRI(com.huawei.spg2800.v100r002c03.QueryLRIRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryLRIResponse queryLRI(QueryLRIRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryLRI");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryLRIResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setRepData(com.huawei.spg2800.v100r002c03.SetRepDataRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setRepData(SetRepDataRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setRepData");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setNPSSBR(com.huawei.spg2800.v100r002c03.SetNPSSBRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setNPSSBR(SetNPSSBRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setNPSSBR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSpeedDial(com.huawei.spg2800.v100r002c03.DeactSpeedDialRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSpeedDial(DeactSpeedDialRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactSpeedDial");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryNPSSBR(com.huawei.spg2800.v100r002c03.QueryNPSSBRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryNPSSBRResponse queryNPSSBR(QueryNPSSBRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryNPSSBR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryNPSSBRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFB(com.huawei.spg2800.v100r002c03.DeactCFBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFB(DeactCFBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySS(com.huawei.spg2800.v100r002c03.QuerySSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySSResponse querySS(QuerySSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#heartbeat(com.huawei.spg2800.v100r002c03.HeartbeatRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType heartbeat(HeartbeatRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation heartbeat");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvFMFM(com.huawei.spg2800.v100r002c03.RmvFMFMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvFMFM(RmvFMFMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvFMFM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryReferralMSG(com.huawei.spg2800.v100r002c03.QueryReferralMSGRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryReferralMSGResponse queryReferralMSG(QueryReferralMSGRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryReferralMSG");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryReferralMSGResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryTNTASAddr(com.huawei.spg2800.v100r002c03.QueryTNTASAddrRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryTNTASAddrResponse queryTNTASAddr(QueryTNTASAddrRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryTNTASAddr");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryTNTASAddrResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFB(com.huawei.spg2800.v100r002c03.QueryCFBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFBResponse queryCFB(QueryCFBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFBResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFU(com.huawei.spg2800.v100r002c03.DeactCFURequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFU(DeactCFURequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFU");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvNPSSBR(com.huawei.spg2800.v100r002c03.RmvNPSSBRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvNPSSBR(RmvNPSSBRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvNPSSBR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySub(com.huawei.spg2800.v100r002c03.QuerySubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySubResponse querySub(QuerySubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySubResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPreProvDev2Sub(com.huawei.spg2800.v100r002c03.AddPreProvDev2SubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPreProvDev2Sub(AddPreProvDev2SubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addPreProvDev2Sub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvDeviceTN(com.huawei.spg2800.v100r002c03.RmvDeviceTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvDeviceTN(RmvDeviceTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvDeviceTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFVM(com.huawei.spg2800.v100r002c03.ActCFVMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFVM(ActCFVMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFVM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actNPAS(com.huawei.spg2800.v100r002c03.ActNPASRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actNPAS(ActNPASRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actNPAS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#regComSS(com.huawei.spg2800.v100r002c03.RegComSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType regComSS(RegComSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation regComSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryPSISub(com.huawei.spg2800.v100r002c03.QueryPSISubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryPSISubResponse queryPSISub(QueryPSISubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryPSISub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryPSISubResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#preProv4HSS(com.huawei.spg2800.v100r002c03.PreProv4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType preProv4HSS(PreProv4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation preProv4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFNR(com.huawei.spg2800.v100r002c03.QueryCFNRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFNRResponse queryCFNR(QueryCFNRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFNR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFNRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvSiFC(com.huawei.spg2800.v100r002c03.RmvSiFCRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvSiFC(RmvSiFCRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvSiFC");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySiFC(com.huawei.spg2800.v100r002c03.QuerySiFCRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySiFCResponse querySiFC(QuerySiFCRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySiFC");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySiFCResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modFMFM(com.huawei.spg2800.v100r002c03.ModFMFMRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modFMFM(ModFMFMRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modFMFM");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryChargeID(com.huawei.spg2800.v100r002c03.QueryChargeIDRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryChargeIDResponse queryChargeID(QueryChargeIDRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryChargeID");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryChargeIDResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setESRN(com.huawei.spg2800.v100r002c03.SetESRNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setESRN(SetESRNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setESRN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactTN(com.huawei.spg2800.v100r002c03.DeactTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactTN(DeactTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSCR(com.huawei.spg2800.v100r002c03.ActSCRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSCR(ActSCRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actSCR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPSISub(com.huawei.spg2800.v100r002c03.AddPSISubRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPSISub(AddPSISubRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addPSISub");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryRegisteredService(com.huawei.spg2800.v100r002c03.QueryRegisteredServiceRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryRegisteredServiceResponse queryRegisteredService(QueryRegisteredServiceRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryRegisteredService");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryRegisteredServiceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actNPAS4HSS(com.huawei.spg2800.v100r002c03.ActNPAS4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actNPAS4HSS(ActNPAS4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actNPAS4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addCAPSCSCF(com.huawei.spg2800.v100r002c03.AddCAPSCSCFRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addCAPSCSCF(AddCAPSCSCFRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addCAPSCSCF");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFS(com.huawei.spg2800.v100r002c03.QueryCFSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFSResponse queryCFS(QueryCFSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFSResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryServiceData(com.huawei.spg2800.v100r002c03.QueryServiceDataRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryServiceDataResponse queryServiceData(QueryServiceDataRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryServiceData");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryServiceDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFNR(com.huawei.spg2800.v100r002c03.ActCFNRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFNR(ActCFNRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFNR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryDevRegStatus(com.huawei.spg2800.v100r002c03.QueryDevRegStatusRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryDevRegStatusResponse queryDevRegStatus(QueryDevRegStatusRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryDevRegStatus");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryDevRegStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#preProv(com.huawei.spg2800.v100r002c03.PreProvRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType preProv(PreProvRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation preProv");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryDRCW(com.huawei.spg2800.v100r002c03.QueryDRCWRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryDRCWResponse queryDRCW(QueryDRCWRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryDRCW");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryDRCWResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addReferralMSG(com.huawei.spg2800.v100r002c03.AddReferralMSGRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addReferralMSG(AddReferralMSGRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addReferralMSG");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySnowBird(com.huawei.spg2800.v100r002c03.QuerySnowBirdRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySnowBirdResponse querySnowBird(QuerySnowBirdRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySnowBird");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySnowBirdResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#swapTN(com.huawei.spg2800.v100r002c03.SwapTNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType swapTN(SwapTNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation swapTN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryESRN(com.huawei.spg2800.v100r002c03.QueryESRNRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryESRNResponse queryESRN(QueryESRNRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryESRN");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryESRNResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactCFDA(com.huawei.spg2800.v100r002c03.DeactCFDARequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactCFDA(DeactCFDARequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactCFDA");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySCR(com.huawei.spg2800.v100r002c03.QuerySCRRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySCRResponse querySCR(QuerySCRRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySCR");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySCRResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actSpeedDial(com.huawei.spg2800.v100r002c03.ActSpeedDialRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actSpeedDial(ActSpeedDialRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actSpeedDial");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addPreProvDev2Sub4HSS(com.huawei.spg2800.v100r002c03.AddPreProvDev2Sub4HSSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addPreProvDev2Sub4HSS(AddPreProvDev2Sub4HSSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addPreProvDev2Sub4HSS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#querySB(com.huawei.spg2800.v100r002c03.QuerySBRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QuerySBResponse querySB(QuerySBRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation querySB");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QuerySBResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFS(com.huawei.spg2800.v100r002c03.ActCFSRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFS(ActCFSRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#modPUSIAS(com.huawei.spg2800.v100r002c03.ModPUSIASRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType modPUSIAS(ModPUSIASRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation modPUSIAS");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#addTN2Device(com.huawei.spg2800.v100r002c03.AddTN2DeviceRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType addTN2Device(AddTN2DeviceRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation addTN2Device");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#deactSnowBird(com.huawei.spg2800.v100r002c03.DeactSnowBirdRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType deactSnowBird(DeactSnowBirdRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation deactSnowBird");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setLRI(com.huawei.spg2800.v100r002c03.SetLRIRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setLRI(SetLRIRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setLRI");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#changeUName(com.huawei.spg2800.v100r002c03.ChangeUNameRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType changeUName(ChangeUNameRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation changeUName");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFU(com.huawei.spg2800.v100r002c03.ActCFURequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFU(ActCFURequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFU");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#queryCFU(com.huawei.spg2800.v100r002c03.QueryCFURequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.QueryCFUResponse queryCFU(QueryCFURequest body,Authentication header,int header1) { 
        LOG.info("Executing operation queryCFU");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.QueryCFUResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#actCFDA(com.huawei.spg2800.v100r002c03.ActCFDARequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType actCFDA(ActCFDARequest body,Authentication header,int header1) { 
        LOG.info("Executing operation actCFDA");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#setCap(com.huawei.spg2800.v100r002c03.SetCapRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType setCap(SetCapRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation setCap");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.huawei.spg2800.v100r002c03.SPG2800Port#rmvCAPSCSCF(com.huawei.spg2800.v100r002c03.RmvCAPSCSCFRequest  body ,)com.huawei.spg2800.v100r002c03.Authentication  header ,)int  header1 )*
     */
    public com.huawei.spg2800.v100r002c03.GenericResponseType rmvCAPSCSCF(RmvCAPSCSCFRequest body,Authentication header,int header1) { 
        LOG.info("Executing operation rmvCAPSCSCF");
        System.out.println(body);
        System.out.println(header);
        System.out.println(header1);
        try {
            com.huawei.spg2800.v100r002c03.GenericResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
